import { eq } from 'drizzle-orm';
import { db } from '../db/index.js';
import * as schema from '../db/schema/index.js';

export const paymentMethodKeys = [
  'cash',
  'mtn_mobile_money',
  'airtel_money',
  'bank_card',
  'bank_transfer',
] as const;

export type PaymentMethodKey = (typeof paymentMethodKeys)[number];

export const defaultPaymentMethods: Record<PaymentMethodKey, boolean> = {
  cash: true,
  mtn_mobile_money: true,
  airtel_money: true,
  bank_card: true,
  bank_transfer: true,
};

export const defaultAppSettings = {
  businessName: 'Evaya Naturals',
  logoDataUrl: null as string | null,
  phone: '+256 700 000 001',
  email: 'hello@evaya.ug',
  address: 'Kampala, Uganda',
  currency: 'UGX',
  expiryAlertDays: 30,
  lowStockDefaultThreshold: 5,
  receiptFooterMessage: 'Thank you for choosing Evaya Naturals.',
  reportFooterMessage: 'Internal use only. Generated by Evaya Naturals.',
  paymentMethods: defaultPaymentMethods,
};

export function normalizePaymentMethods(value: unknown): Record<PaymentMethodKey, boolean> {
  const incoming = typeof value === 'object' && value ? value as Record<string, unknown> : {};
  return paymentMethodKeys.reduce((result, key) => {
    result[key] = incoming[key] === undefined ? defaultPaymentMethods[key] : Boolean(incoming[key]);
    return result;
  }, {} as Record<PaymentMethodKey, boolean>);
}

export async function getAppSettings() {
  const [settings] = await db.select().from(schema.appSettings).where(eq(schema.appSettings.id, 'app'));

  if (!settings) {
    return {
      id: 'app',
      ...defaultAppSettings,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
  }

  return {
    ...settings,
    logoDataUrl: settings.logoDataUrl ?? null,
    address: settings.address ?? '',
    receiptFooterMessage: settings.receiptFooterMessage ?? '',
    reportFooterMessage: settings.reportFooterMessage ?? '',
    paymentMethods: normalizePaymentMethods(settings.paymentMethods),
  };
}

export async function updateAppSettings(
  patch: Partial<{
    businessName: string;
    logoDataUrl: string | null;
    phone: string;
    email: string;
    address: string | null;
    currency: string;
    expiryAlertDays: number;
    lowStockDefaultThreshold: number;
    receiptFooterMessage: string | null;
    reportFooterMessage: string | null;
    paymentMethods: Record<PaymentMethodKey, boolean>;
  }>,
) {
  const current = await getAppSettings();
  const next = {
    ...current,
    ...patch,
    logoDataUrl: patch.logoDataUrl === undefined ? current.logoDataUrl : patch.logoDataUrl,
    address: patch.address === undefined ? current.address : patch.address,
    receiptFooterMessage: patch.receiptFooterMessage === undefined ? current.receiptFooterMessage : patch.receiptFooterMessage,
    reportFooterMessage: patch.reportFooterMessage === undefined ? current.reportFooterMessage : patch.reportFooterMessage,
    paymentMethods: patch.paymentMethods ? normalizePaymentMethods(patch.paymentMethods) : current.paymentMethods,
    updatedAt: new Date().toISOString(),
  };

  await db.update(schema.appSettings)
    .set({
      businessName: next.businessName,
      logoDataUrl: next.logoDataUrl,
      phone: next.phone,
      email: next.email,
      address: next.address,
      currency: next.currency,
      expiryAlertDays: next.expiryAlertDays,
      lowStockDefaultThreshold: next.lowStockDefaultThreshold,
      receiptFooterMessage: next.receiptFooterMessage,
      reportFooterMessage: next.reportFooterMessage,
      paymentMethods: next.paymentMethods,
      updatedAt: next.updatedAt,
    })
    .where(eq(schema.appSettings.id, 'app'));

  return getAppSettings();
}
