import { beforeAll, beforeEach, describe, expect, it } from 'vitest';
import bcrypt from 'bcryptjs';
import { and, eq } from 'drizzle-orm';
import app from './index';
import { db } from './db';
import { initializeDatabase } from './db/init';
import * as schema from './db/schema';

async function json(response: Response) {
  return response.json() as Promise<Record<string, any>>;
}

async function login(email: string, password: string) {
  const response = await app.request('/api/auth/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });

  expect(response.status).toBe(200);
  const payload = await json(response);
  return payload.token as string;
}

async function createUser(roleName: string, email: string, branchId: string) {
  const [role] = await db.select().from(schema.roles).where(eq(schema.roles.name, roleName));
  expect(role).toBeDefined();
  const passwordHash = await bcrypt.hash('secret123', 10);
  const [user] = await db.insert(schema.users).values({
    email,
    passwordHash,
    firstName: roleName.replace(/\s+/g, ''),
    lastName: 'POS',
    phone: '+256700000222',
    roleId: role.id,
    branchId,
    isActive: true,
  }).returning();
  return user;
}

async function createCategory(adminToken: string, name: string) {
  void adminToken;
  return { id: `legacy-category-${name.toLowerCase().replace(/\s+/g, '-')}` };
}

async function createProduct(adminToken: string, branchId: string, _categoryId: string, name: string) {
  const response = await app.request('/api/catalog/products', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({
      name,
      sku: `${name.slice(0, 3).toUpperCase()}-001`,
      barcode: `${Date.now()}${Math.floor(Math.random() * 1000)}`,
      unitType: 'kg',
      sellingPrice: 12000,
      costPrice: 6000,
      lowStockThreshold: 3,
      visibilityBranchIds: [branchId],
    }),
  });
  expect(response.status).toBe(201);
  return (await json(response)).product;
}

async function receiveBatch(adminToken: string, payload: Record<string, unknown>) {
  const response = await app.request('/api/catalog/inventory/batches', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify(payload),
  });
  expect(response.status).toBe(201);
  return (await json(response)).batch;
}

async function openShift(token: string, openingCash = 10000) {
  const response = await app.request('/api/pos/shift/open', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({ openingCash }),
  });
  expect(response.status).toBe(201);
  return (await json(response)).shift;
}

async function createCustomer(token: string, payload: { name: string; phone: string; whatsappNumber?: string; email?: string; isActive?: boolean }) {
  const response = await app.request('/api/pos/customers', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(payload),
  });
  expect(response.status).toBe(201);
  return (await json(response)).customer;
}

async function resetAppSettings() {
  await db.update(schema.appSettings)
    .set({
      businessName: 'Evaya Naturals',
      logoDataUrl: null,
      phone: '+256 700 000 001',
      email: 'hello@evaya.ug',
      address: 'Kampala, Uganda',
      currency: 'UGX',
      expiryAlertDays: 30,
      lowStockDefaultThreshold: 5,
      receiptFooterMessage: 'Thank you for choosing Evaya Naturals.',
      reportFooterMessage: 'Internal use only. Generated by Evaya Naturals.',
      paymentMethods: {
        cash: true,
        mtn_mobile_money: true,
        airtel_money: true,
        bank_card: true,
        bank_transfer: true,
      },
    })
    .where(eq(schema.appSettings.id, 'app'));
}

describe('pos slice', () => {
  let adminToken = '';
  let branchId = '';

  beforeAll(async () => {
    await initializeDatabase();
    const [primaryBranch] = await db.select().from(schema.branches).where(eq(schema.branches.name, 'Evaya Naturals'));
    branchId = primaryBranch.id;
    adminToken = await login('admin@evaya.ug', 'admin123');
  });

  beforeEach(async () => {
    await db.delete(schema.sessions);
    await db.delete(schema.auditLogs);
    await db.delete(schema.saleItems);
    await db.delete(schema.sales);
    await db.delete(schema.dailyCloses);
    await db.delete(schema.shifts);
    await db.delete(schema.deliveries);
    await db.delete(schema.expenses);
    await db.delete(schema.broadcasts);
    await db.delete(schema.inventoryMovements);
    await db.delete(schema.inventory);
    await db.delete(schema.batches);
    await db.delete(schema.customers);
    await db.delete(schema.productVisibility);
    await db.delete(schema.products);
    await db.delete(schema.categories).where(eq(schema.categories.name, 'POS Category'));
    await db.delete(schema.categories).where(eq(schema.categories.name, 'Expired Category'));
    await db.delete(schema.users).where(eq(schema.users.email, 'cashier.pos@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'rider.pos@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'accountant.pos@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'manager.pos@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'inventory.pos@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'manager.shift@evaya.ug'));
    await resetAppSettings();
    adminToken = await login('admin@evaya.ug', 'admin123');
  });

  it('supports POS product search for active sellable stock', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Turmeric Soap');
    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + 20);

    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'SOAP-B1',
      expiryDate: futureDate.toISOString(),
      quantityReceived: 10,
      costPrice: 6000,
      sellingPrice: 12000,
    });

    const response = await app.request('/api/pos/products?search=Turmeric', {
      headers: { Authorization: `Bearer ${adminToken}` },
    });
    expect(response.status).toBe(200);
    const payload = await json(response);
    expect(payload.products).toHaveLength(1);
    expect(payload.products[0].availableQuantity).toBe(10);
  });

  it('keeps out-of-stock products visible in POS results with an out-of-stock state', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Cinnamon Blend');

    const response = await app.request('/api/pos/products?search=Cinnamon', {
      headers: { Authorization: `Bearer ${adminToken}` },
    });
    expect(response.status).toBe(200);
    const payload = await json(response);
    expect(payload.products).toHaveLength(1);
    expect(payload.products[0].id).toBe(product.id);
    expect(payload.products[0].availableQuantity).toBe(0);
    expect(payload.products[0].isOutOfStock).toBe(true);
  });

  it('completes a successful cashier sale, deducts FIFO stock, and records movements', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Ginger Tonic');
    const firstExpiry = new Date();
    firstExpiry.setDate(firstExpiry.getDate() + 5);
    const secondExpiry = new Date();
    secondExpiry.setDate(secondExpiry.getDate() + 15);

    const batchOne = await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'TONIC-B1',
      expiryDate: firstExpiry.toISOString(),
      quantityReceived: 2,
      costPrice: 7000,
      sellingPrice: 12000,
    });

    const batchTwo = await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'TONIC-B2',
      expiryDate: secondExpiry.toISOString(),
      quantityReceived: 4,
      costPrice: 7000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');

    const blockedSaleRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        discount: 2000,
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(blockedSaleRes.status).toBe(409);

    const activeShift = await openShift(cashierToken, 12000);

    const saleResponse = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        discount: 2000,
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 3 }],
      }),
    });

    expect(saleResponse.status).toBe(201);
    const salePayload = await json(saleResponse);
    expect(salePayload.receiptNumber).toMatch(/^EVN-/);
    expect(salePayload.sale.total).toBe(34000);

    const [inventory] = await db.select().from(schema.inventory).where(eq(schema.inventory.productId, product.id));
    expect(inventory.quantity).toBe(3);

    const [updatedBatchOne] = await db.select().from(schema.batches).where(eq(schema.batches.id, batchOne.id));
    const [updatedBatchTwo] = await db.select().from(schema.batches).where(eq(schema.batches.id, batchTwo.id));
    expect(updatedBatchOne.quantityRemaining).toBe(0);
    expect(updatedBatchTwo.quantityRemaining).toBe(3);

    const movements = await db.select().from(schema.inventoryMovements).where(eq(schema.inventoryMovements.referenceId, salePayload.sale.id));
    expect(movements).toHaveLength(2);
    expect(movements.every((movement) => movement.movementType === 'sale')).toBe(true);
    expect(movements.every((movement) => movement.referenceType === 'sale')).toBe(true);

    const [persistedSale] = await db.select().from(schema.sales).where(eq(schema.sales.id, salePayload.sale.id));
    expect(persistedSale.shiftId).toBe(activeShift.id);

    const receiptResponse = await app.request(`/api/pos/receipts/${salePayload.sale.id}`, {
      headers: { Authorization: `Bearer ${cashierToken}` },
    });
    expect(receiptResponse.status).toBe(200);
    const receiptPayload = await json(receiptResponse);
    expect(receiptPayload.receipt.items).toHaveLength(2);
  });

  it('rejects checkout with an empty cart before creating a sale', async () => {
    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    await openShift(cashierToken);

    const response = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [],
      }),
    });

    expect(response.status).toBe(400);
    expect((await json(response)).error).toBe('Add at least one item before completing sale');
  });

  it('blocks selling expired stock only', async () => {
    const category = await createCategory(adminToken, 'Expired Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Neem Balm');
    const expiredDate = new Date();
    expiredDate.setDate(expiredDate.getDate() - 1);

    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'BALM-B1',
      expiryDate: expiredDate.toISOString(),
      quantityReceived: 5,
      costPrice: 4000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    await openShift(cashierToken);

    const response = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });

    expect(response.status).toBe(409);
    expect((await json(response)).error).toContain('only has expired stock');
  });

  it('blocks insufficient stock', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Lemongrass Tea');
    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + 12);

    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'TEA-B1',
      expiryDate: futureDate.toISOString(),
      quantityReceived: 2,
      costPrice: 5000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    await openShift(cashierToken);

    const response = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 3 }],
      }),
    });

    expect(response.status).toBe(409);
    expect((await json(response)).error).toContain('Insufficient stock');
  });

  it('reconciles stale inventory quantity from sellable batches during sale checkout', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Rollback Sale Product');
    const batch = await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'ROLLBACK-SALE-B1',
      expiryDate: new Date(Date.now() + 86400000 * 10).toISOString(),
      quantityReceived: 5,
      costPrice: 5000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    await openShift(cashierToken);

    await db.update(schema.inventory)
      .set({ quantity: 0 })
      .where(and(eq(schema.inventory.productId, product.id), eq(schema.inventory.branchId, branchId)));

    const saleRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(saleRes.status).toBe(201);

    const sales = await db.select().from(schema.sales).where(eq(schema.sales.branchId, branchId));
    expect(sales).toHaveLength(1);

    const [reloadedBatch] = await db.select().from(schema.batches).where(eq(schema.batches.id, batch.id));
    expect(reloadedBatch.quantityRemaining).toBe(4);

    const [reloadedInventory] = await db.select().from(schema.inventory).where(and(
      eq(schema.inventory.productId, product.id),
      eq(schema.inventory.branchId, branchId),
    ));
    expect(reloadedInventory.quantity).toBe(4);

    const saleMovements = await db.select().from(schema.inventoryMovements).where(and(
      eq(schema.inventoryMovements.productId, product.id),
      eq(schema.inventoryMovements.branchId, branchId),
      eq(schema.inventoryMovements.movementType, 'sale'),
    ));
    expect(saleMovements).toHaveLength(1);
  });

  it('allows cashier checkout and blocks branch manager from checkout while still allowing POS visibility', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Moringa Tea');
    const futureDate = new Date();
    futureDate.setDate(futureDate.getDate() + 18);

    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'MOR-B1',
      expiryDate: futureDate.toISOString(),
      quantityReceived: 10,
      costPrice: 4000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    await createUser('Branch Manager', 'manager.pos@evaya.ug', branchId);

    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    const managerToken = await login('manager.pos@evaya.ug', 'secret123');

    const cashierToday = await app.request('/api/pos/sales/today', {
      headers: { Authorization: `Bearer ${cashierToken}` },
    });
    expect(cashierToday.status).toBe(200);

    const managerToday = await app.request('/api/pos/sales/today', {
      headers: { Authorization: `Bearer ${managerToken}` },
    });
    expect(managerToday.status).toBe(200);

    await openShift(cashierToken);

    const cashierCheckout = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(cashierCheckout.status).toBe(201);

    const managerCheckout = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${managerToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(managerCheckout.status).toBe(403);
  });

  it('allows only admin, branch manager, and cashier to view customers', async () => {
    const customer = await createCustomer(adminToken, {
      name: 'Visibility Customer',
      phone: '+256700333444',
      whatsappNumber: '+256700333444',
    });
    expect(customer.id).toBeDefined();

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    await createUser('Branch Manager', 'manager.pos@evaya.ug', branchId);

    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    const managerToken = await login('manager.pos@evaya.ug', 'secret123');

    expect((await app.request('/api/pos/customers', { headers: { Authorization: `Bearer ${cashierToken}` } })).status).toBe(200);
    expect((await app.request('/api/pos/customers', { headers: { Authorization: `Bearer ${managerToken}` } })).status).toBe(200);
    expect((await app.request('/api/pos/expenses', { headers: { Authorization: `Bearer ${cashierToken}` } })).status).toBe(403);
  });

  it('opens shifts, blocks second active shift, closes with variance, and enforces approval permissions', async () => {
    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const manager = await createUser('Branch Manager', 'manager.shift@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    const managerToken = await login(manager.email, 'secret123');

    const openRes = await app.request('/api/pos/shift/open', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({ openingCash: 15000 }),
    });
    expect(openRes.status).toBe(201);
    const activeShift = (await json(openRes)).shift;

    const duplicateOpenRes = await app.request('/api/pos/shift/open', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({ openingCash: 5000 }),
    });
    expect(duplicateOpenRes.status).toBe(409);

    const currentShiftRes = await app.request('/api/pos/shift/current', {
      headers: { Authorization: `Bearer ${cashierToken}` },
    });
    expect(currentShiftRes.status).toBe(200);
    expect((await json(currentShiftRes)).shift.id).toBe(activeShift.id);

    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Shift Test Product');
    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'SHIFT-B1',
      expiryDate: new Date(Date.now() + 86400000 * 7).toISOString(),
      quantityReceived: 4,
      costPrice: 5000,
      sellingPrice: 12000,
    });

    const saleRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 2 }],
      }),
    });
    expect(saleRes.status).toBe(201);

    const closeRes = await app.request('/api/pos/shift/close', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        countedCash: 38000,
        notes: 'Drawer reconciled',
      }),
    });
    expect(closeRes.status).toBe(200);
    const closedShift = (await json(closeRes)).shift;
    expect(closedShift.status).toBe('closed');
    expect(closedShift.expectedCash).toBe(39000);
    expect(closedShift.variance).toBe(-1000);

    const [dailyClose] = await db.select().from(schema.dailyCloses).where(eq(schema.dailyCloses.shiftId, activeShift.id));
    expect(dailyClose.cashExpected).toBe(39000);
    expect(dailyClose.cashCounted).toBe(38000);
    expect(dailyClose.difference).toBe(-1000);

    const approveRes = await app.request(`/api/pos/shift/${activeShift.id}/approve`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${managerToken}` },
    });
    expect(approveRes.status).toBe(200);
    expect((await json(approveRes)).shift.status).toBe('approved');

    const cashierApproveRes = await app.request(`/api/pos/shift/${activeShift.id}/approve`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${cashierToken}` },
    });
    expect(cashierApproveRes.status).toBe(403);
  });

  it('supports customer create edit deactivate and search', async () => {
    const created = await createCustomer(adminToken, {
      name: 'Anita Herbal',
      phone: '+256700111222',
      whatsappNumber: '+256700111222',
      email: 'anita@evaya.ug',
    });

    const updateRes = await app.request(`/api/pos/customers/${created.id}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        name: 'Anita Wellness',
        isActive: false,
      }),
    });
    expect(updateRes.status).toBe(200);
    expect((await json(updateRes)).customer.isActive).toBe(false);

    const searchRes = await app.request('/api/pos/customers?search=111222&includeInactive=true', {
      headers: { Authorization: `Bearer ${adminToken}` },
    });
    expect(searchRes.status).toBe(200);
    const searchPayload = await json(searchRes);
    expect(searchPayload.customers).toHaveLength(1);
    expect(searchPayload.customers[0].name).toBe('Anita Wellness');
  });

  it('links customer to sale, supports quick customer creation, and includes customer on receipt', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'Baobab Mix');
    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'BAO-B1',
      expiryDate: new Date(Date.now() + 86400000 * 20).toISOString(),
      quantityReceived: 10,
      costPrice: 5000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    await openShift(cashierToken);

    const savedCustomer = await createCustomer(adminToken, {
      name: 'Grace Active',
      phone: '+256700555777',
    });

    const saleWithCustomerRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        customerId: savedCustomer.id,
        paymentMethod: 'cash',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(saleWithCustomerRes.status).toBe(201);
    const saleWithCustomer = await json(saleWithCustomerRes);

    const receiptRes = await app.request(`/api/pos/receipts/${saleWithCustomer.sale.id}`, {
      headers: { Authorization: `Bearer ${cashierToken}` },
    });
    expect(receiptRes.status).toBe(200);
    const receiptPayload = await json(receiptRes);
    expect(receiptPayload.receipt.customerName).toBe('Grace Active');

    const quickSaleRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        quickCustomer: {
          name: 'Quick Walkin',
          phone: '+256700999111',
        },
        paymentMethod: 'mtn_mobile_money',
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(quickSaleRes.status).toBe(201);
    const [quickCustomer] = await db.select().from(schema.customers).where(eq(schema.customers.phone, '+256700999111'));
    expect(quickCustomer.name).toBe('Quick Walkin');
  });

  it('returns today sales history with payment filters', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const product = await createProduct(adminToken, branchId, category.id, 'History Tonic');
    await receiveBatch(adminToken, {
      productId: product.id,
      branchId,
      batchNumber: 'HIS-B1',
      expiryDate: new Date(Date.now() + 86400000 * 10).toISOString(),
      quantityReceived: 10,
      costPrice: 5000,
      sellingPrice: 12000,
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');
    await openShift(cashierToken);

    await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({ paymentMethod: 'cash', items: [{ productId: product.id, quantity: 1 }] }),
    });

    const cardSaleRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({ paymentMethod: 'bank_card', items: [{ productId: product.id, quantity: 1 }] }),
    });
    const cardSale = await json(cardSaleRes);

    const filteredRes = await app.request(`/api/pos/sales/today?paymentMethod=bank_card&receiptSearch=${cardSale.receiptNumber}`, {
      headers: { Authorization: `Bearer ${cashierToken}` },
    });
    expect(filteredRes.status).toBe(200);
    const filteredPayload = await json(filteredRes);
    expect(filteredPayload.sales).toHaveLength(1);
    expect(filteredPayload.sales[0].paymentMethod).toBe('bank_card');
    expect(filteredPayload.sales[0].receiptNumber).toBe(cardSale.receiptNumber);
  });

  it('prepares WhatsApp broadcast links, reports missing SMS provider, and enforces broadcast permissions', async () => {
    const customerOne = await createCustomer(adminToken, {
      name: 'Broadcast One',
      phone: '+256700100100',
      whatsappNumber: '+256 700-100-100',
    });
    const customerTwo = await createCustomer(adminToken, {
      name: 'Broadcast Two',
      phone: '+256700200200',
    });

    await createUser('Cashier', 'cashier.pos@evaya.ug', branchId);
    const cashierToken = await login('cashier.pos@evaya.ug', 'secret123');

    const whatsappRes = await app.request('/api/pos/customers/broadcasts', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        channel: 'whatsapp',
        customerIds: [customerOne.id, customerTwo.id],
        messageBody: 'Your herbs are back in stock.',
      }),
    });
    expect(whatsappRes.status).toBe(201);
    const whatsappPayload = await json(whatsappRes);
    expect(whatsappPayload.statusLabel).toContain('Prepared WhatsApp links');
    expect(whatsappPayload.statusLabel).toContain('do not have WhatsApp numbers');
    expect(whatsappPayload.links).toHaveLength(1);
    expect(whatsappPayload.links[0].url).toBe('https://wa.me/256700100100?text=Your%20herbs%20are%20back%20in%20stock.');

    const noWhatsappRes = await app.request('/api/pos/customers/broadcasts', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        channel: 'whatsapp',
        customerIds: [customerTwo.id],
        messageBody: 'Need a WhatsApp number.',
      }),
    });
    expect(noWhatsappRes.status).toBe(400);
    expect((await json(noWhatsappRes)).error).toBe('Selected customers do not have WhatsApp numbers');

    const smsRes = await app.request('/api/pos/customers/broadcasts', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        channel: 'sms',
        customerIds: [customerOne.id],
        messageBody: 'Store update.',
      }),
    });
    expect(smsRes.status).toBe(201);
    expect((await json(smsRes)).message).toBe('SMS provider not configured');

    const cashierBroadcastRes = await app.request('/api/pos/customers/broadcasts', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        channel: 'whatsapp',
        customerIds: [customerOne.id],
        messageBody: 'Not allowed.',
      }),
    });
    expect(cashierBroadcastRes.status).toBe(403);
  });

  it('excludes inactive products from low-stock reports', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const activeProduct = await createProduct(adminToken, branchId, category.id, 'Active Low Stock Product');
    const inactiveProduct = await createProduct(adminToken, branchId, category.id, 'Inactive Low Stock Product');

    await receiveBatch(adminToken, {
      productId: activeProduct.id,
      branchId,
      batchNumber: 'BATCH-001',
      expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      quantityReceived: 2,
      costPrice: 6000,
      sellingPrice: 12000,
    });

    await receiveBatch(adminToken, {
      productId: inactiveProduct.id,
      branchId,
      batchNumber: 'BATCH-002',
      expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      quantityReceived: 2,
      costPrice: 6000,
      sellingPrice: 12000,
    });

    const deactivateRes = await app.request(`/api/catalog/products/${inactiveProduct.id}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({ isActive: false }),
    });
    expect(deactivateRes.status).toBe(200);

    const reportRes = await app.request('/api/pos/reports/summary', {
      headers: { Authorization: `Bearer ${adminToken}` },
    });
    expect(reportRes.status).toBe(200);
    const report = await json(reportRes);

    const lowStockProductNames = report.lowStockSummary.items.map((item: any) => item.productName);
    expect(lowStockProductNames).toContain('Active Low Stock Product');
    expect(lowStockProductNames).not.toContain('Inactive Low Stock Product');
    expect(report.lowStockSummary.count).toBe(report.lowStockSummary.items.length);
  });

  it('excludes products without active branch visibility from low-stock reports', async () => {
    const category = await createCategory(adminToken, 'POS Category');
    const hiddenProduct = await createProduct(adminToken, branchId, category.id, 'Hidden Low Stock Product');

    await receiveBatch(adminToken, {
      productId: hiddenProduct.id,
      branchId,
      batchNumber: 'BATCH-HIDDEN',
      expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
      quantityReceived: 2,
      costPrice: 6000,
      sellingPrice: 12000,
    });

    await db.delete(schema.productVisibility)
      .where(and(
        eq(schema.productVisibility.productId, hiddenProduct.id),
        eq(schema.productVisibility.branchId, branchId),
      ));

    const reportRes = await app.request('/api/pos/reports/summary', {
      headers: { Authorization: `Bearer ${adminToken}` },
    });
    expect(reportRes.status).toBe(200);
    const report = await json(reportRes);

    const lowStockProductNames = report.lowStockSummary.items.map((item: any) => item.productName);
    expect(lowStockProductNames).not.toContain('Hidden Low Stock Product');
    expect(report.lowStockSummary.count).toBe(report.lowStockSummary.items.length);
  });
});
