import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import bcrypt from 'bcryptjs';
import { eq } from 'drizzle-orm';
import app from './index';
import { db } from './db';
import { initializeDatabase } from './db/init';
import * as schema from './db/schema';

async function json(response: Response) {
  return response.json() as Promise<Record<string, any>>;
}

async function login(email: string, password: string) {
  const response = await app.request('/api/auth/login', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });
  expect(response.status).toBe(200);
  return (await json(response)).token as string;
}

async function createUser(roleName: string, email: string, branchId: string) {
  const [role] = await db.select().from(schema.roles).where(eq(schema.roles.name, roleName));
  const passwordHash = await bcrypt.hash('secret123', 10);
  const [user] = await db.insert(schema.users).values({
    email,
    passwordHash,
    firstName: roleName.replace(/\s+/g, ''),
    lastName: 'Settings',
    phone: '+256700004444',
    roleId: role.id,
    branchId,
    isActive: true,
  }).returning();
  return user;
}

async function createCategory(adminToken: string, name: string) {
  const response = await app.request('/api/catalog/categories', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({ name }),
  });
  expect(response.status).toBe(201);
  return (await json(response)).category;
}

async function createProduct(adminToken: string, branchId: string, categoryId: string) {
  const response = await app.request('/api/catalog/products', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({
      name: `Settings Product ${Date.now()}`,
      sku: `SET-${Date.now()}`,
      categoryId,
      unitType: 'kg',
      sellingPrice: 12000,
      costPrice: 6000,
      lowStockThreshold: 3,
      visibilityBranchIds: [branchId],
    }),
  });
  expect(response.status).toBe(201);
  return (await json(response)).product;
}

async function receiveBatch(adminToken: string, branchId: string, productId: string) {
  const response = await app.request('/api/catalog/inventory/batches', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${adminToken}`,
    },
    body: JSON.stringify({
      productId,
      branchId,
      batchNumber: `SET-BATCH-${Date.now()}`,
      expiryDate: new Date(Date.now() + 86400000 * 14).toISOString(),
      quantityReceived: 5,
      costPrice: 6000,
      sellingPrice: 12000,
    }),
  });
  expect(response.status).toBe(201);
}

async function resetAppSettings() {
  await db.update(schema.appSettings)
    .set({
      businessName: 'Evaya Naturals',
      logoDataUrl: null,
      phone: '+256 700 000 001',
      email: 'hello@evaya.ug',
      address: 'Kampala, Uganda',
      currency: 'UGX',
      expiryAlertDays: 30,
      lowStockDefaultThreshold: 5,
      receiptFooterMessage: 'Thank you for choosing Evaya Naturals.',
      reportFooterMessage: 'Internal use only. Generated by Evaya Naturals.',
      paymentMethods: {
        cash: true,
        mtn_mobile_money: true,
        airtel_money: true,
        bank_card: true,
        bank_transfer: true,
      },
    })
    .where(eq(schema.appSettings.id, 'app'));
}

describe('settings slice', () => {
  let adminToken = '';
  let branchId = '';

  beforeAll(async () => {
    await initializeDatabase();
    const [branch] = await db.select().from(schema.branches).where(eq(schema.branches.name, 'Evaya Naturals'));
    branchId = branch.id;
    adminToken = await login('admin@evaya.ug', 'admin123');
  });

  beforeEach(async () => {
    await db.delete(schema.sessions);
    await db.delete(schema.auditLogs);
    await db.delete(schema.saleItems);
    await db.delete(schema.sales);
    await db.delete(schema.shifts);
    await db.delete(schema.inventoryMovements);
    await db.delete(schema.inventory);
    await db.delete(schema.batches);
    await db.delete(schema.productVisibility);
    await db.delete(schema.products);
    await db.delete(schema.categories).where(eq(schema.categories.name, 'Settings Test Category'));
    await db.delete(schema.users).where(eq(schema.users.email, 'manager.settings@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'cashier.settings@evaya.ug'));
    await db.delete(schema.users).where(eq(schema.users.email, 'new.staff@evaya.ug'));
    await resetAppSettings();
    adminToken = await login('admin@evaya.ug', 'admin123');
  });

  afterAll(async () => {
    await resetAppSettings();
  });

  it('returns and updates admin settings while keeping public settings available', async () => {
    await createUser('Branch Manager', 'manager.settings@evaya.ug', branchId);
    const managerToken = await login('manager.settings@evaya.ug', 'secret123');

    const forbiddenRes = await app.request('/api/settings', {
      headers: { Authorization: `Bearer ${managerToken}` },
    });
    expect(forbiddenRes.status).toBe(403);

    const settingsRes = await app.request('/api/settings', {
      headers: { Authorization: `Bearer ${adminToken}` },
    });
    expect(settingsRes.status).toBe(200);

    const businessRes = await app.request('/api/settings/business-profile', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        businessName: 'Evaya Naturals Shop',
        logoDataUrl: 'data:image/svg+xml;base64,ZXZheWE=',
        phone: '+256700000999',
        email: 'shop@evaya.ug',
        address: 'Bukoto, Kampala',
      }),
    });
    expect(businessRes.status).toBe(200);

    const systemRes = await app.request('/api/settings/system', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        expiryAlertDays: 21,
        lowStockDefaultThreshold: 4,
        receiptFooterMessage: 'Receipt footer',
        reportFooterMessage: 'Report footer',
      }),
    });
    expect(systemRes.status).toBe(200);

    const publicRes = await app.request('/api/settings/public');
    expect(publicRes.status).toBe(200);
    const publicPayload = await json(publicRes);
    expect(publicPayload.businessProfile.businessName).toBe('Evaya Naturals Shop');
    expect(publicPayload.systemSettings.receiptFooterMessage).toBe('Receipt footer');
  });

  it('creates, updates, deactivates, and resets staff users', async () => {
    const createRes = await app.request('/api/settings/staff', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        firstName: 'New',
        lastName: 'Staff',
        email: 'new.staff@evaya.ug',
        phone: '+256700000333',
        roleId: (await db.select().from(schema.roles).where(eq(schema.roles.name, 'Cashier')))[0].id,
        password: 'welcome123',
        isActive: true,
      }),
    });
    expect(createRes.status).toBe(201);
    const createdUser = (await json(createRes)).user;

    const updateRes = await app.request(`/api/settings/staff/${createdUser.id}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        firstName: 'Updated',
        isActive: false,
      }),
    });
    expect(updateRes.status).toBe(200);
    expect((await json(updateRes)).user.isActive).toBe(false);

    const activateRes = await app.request(`/api/settings/staff/${createdUser.id}`, {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        isActive: true,
      }),
    });
    expect(activateRes.status).toBe(200);

    const resetRes = await app.request(`/api/settings/staff/${createdUser.id}/reset-password`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        password: 'newsecret123',
      }),
    });
    expect(resetRes.status).toBe(200);

    const loginToken = await login('new.staff@evaya.ug', 'newsecret123');
    expect(loginToken).toBeTruthy();
  });

  it('blocks disabled payment methods at checkout', async () => {
    await createUser('Cashier', 'cashier.settings@evaya.ug', branchId);
    const cashierToken = await login('cashier.settings@evaya.ug', 'secret123');

    const methodsRes = await app.request('/api/settings/payment-methods', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${adminToken}`,
      },
      body: JSON.stringify({
        cash: true,
        mtn_mobile_money: false,
        airtel_money: true,
        bank_card: true,
        bank_transfer: true,
      }),
    });
    expect(methodsRes.status).toBe(200);

    const category = await createCategory(adminToken, 'Settings Test Category');
    const product = await createProduct(adminToken, branchId, category.id);
    await receiveBatch(adminToken, branchId, product.id);

    const shiftRes = await app.request('/api/pos/shift/open', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({ openingCash: 10000 }),
    });
    expect(shiftRes.status).toBe(201);

    const saleRes = await app.request('/api/pos/sales', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${cashierToken}`,
      },
      body: JSON.stringify({
        paymentMethod: 'mtn_mobile_money',
        discount: 0,
        items: [{ productId: product.id, quantity: 1 }],
      }),
    });
    expect(saleRes.status).toBe(409);
    expect((await json(saleRes)).error).toContain('disabled');
  });
});
